web:
  image: "aojstatusbroadcaster:1.0-SNAPSHOT"
  ports:
    - "10052:10052"
nginx:
  image: "nginx"
  ports:
    - "9000:80"
  links:
    - web
  volumes:
    - "./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
